blank_issues_enabled: true
contact_links:
  - name: ğŸ“š ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
    url: https://github.com/tokane888/go-repository-template/blob/main/README.md
    about: ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã®æ¦‚è¦ã‚„ä½¿ã„æ–¹ã«ã¤ã„ã¦
  - name: ğŸ’¬ ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³
    url: https://github.com/tokane888/go-repository-template/discussions
    about: ä¸€èˆ¬çš„ãªè³ªå•ã‚„è­°è«–ã¯ã“ã¡ã‚‰ã§